### Consulta POST Api Node
POST http://localhost:5001/api/v1/auth/login
Content-Type: application/json

{
    "email": "franklynortega@gmail.com",
    "password": "123123"
}

###
POST http://localhost:5001/api/v1/auth/register
Content-Type: application/json

{
    "email": "franklynortega@gmail.com",
    "password": "123123123"
}
###  

